system:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: Management_system
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
